export { authApi } from './services/auth'
export { clienteApi } from './services/clientes'
export { suministroApi } from './services/suministros'
export { consumoApi } from './services/consumos'
export { simulacionApi } from './services/simulaciones'
export { artefactoApi } from './services/artefactos'
export { tarifaApi } from './services/tarifas'
export { reclamoApi } from './services/reclamos'
